### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by BigDeepBlue** [Fox13th/ugc_service#3]
Добрый день! Есть несколько замечаний

1. https://github.com/Fox13th/ugc_service/blob/e958ff4e20d8b97f0c9c349c3624f0f5755665d9/src/service/kafka_s.py#L20 Лучше в файл логировать через `logging`, в консоли легко потерять сообщения
2. https://github.com/Fox13th/ugc_service/blob/e958ff4e20d8b97f0c9c349c3624f0f5755665d9/src/api/v1/statistics.py#L21 Для http-статуов лучше использовать константы из [HTTPStatus](https://docs.python.org/3/library/http.html#http-status-codes) это немного повышает читаемость
3. https://github.com/Fox13th/ugc_service/blob/e958ff4e20d8b97f0c9c349c3624f0f5755665d9/src/api/v1/statistics.py#L24  Лучше подключить sentry и [логировать](https://docs.sentry.io/platforms/python/usage/#capturing-errors) туда, это упростит дебаг за счет более развернутых логов или хотя бы через `logging` в файл
4. https://github.com/Fox13th/ugc_service/blob/e958ff4e20d8b97f0c9c349c3624f0f5755665d9/src/api/v1/statistics.py#L12 API не хватает авторизации, также желательно написать на него тест/тесты

**Comment by Fox13th** [comment]
closed
